[package]
name = "codly"
version = "1.0.0"
entrypoint = "codly.typ"
authors = ["Dherse"]
license = "MIT"
description = "Codly is a beautiful code presentation template."
repository = "https://github.com/Dherse/codly"
exclude = ["example/*", "demo.png", "docs/*", "docs.pdf", "test/*" ]
compiler = "0.9.0"
keywords = [ "code", "pretty", "template", "raw" ]